import React, { useState } from 'react';
import { Link, useForm } from '@inertiajs/react';

const Create = () => {
    const { data, setData, post, errors, processing } = useForm({
        title: '',
        slug: '',
        meta_description: '',
        page_type: 'modular',
        is_published: false,
        sections: []
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route('pages.store'));
    };

    return (
        <>
            <div className="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h1 className="text-muted mb-1">Create Page</h1>
                    <p className="text-muted mb-0">Build a dynamic page with reusable sections</p>
                </div>
            </div>
            
            <div className="card">
                <form onSubmit={handleSubmit}>
                    <div className="card-body">
                        <div className="row">
                            <div className="mb-3 col-md-6">
                                <label className="form-label">Page Title <span className='text-danger'>*</span></label>
                                <input
                                    type="text"
                                    className="form-control"
                                    value={data.title}
                                    onChange={e => setData('title', e.target.value)}
                                    placeholder="About Us"
                                />
                                {errors.title && <div className="text-danger small">{errors.title}</div>}
                                <div className="form-text">The main title of your page</div>
                            </div>

                            <div className="mb-3 col-md-6">
                                <label className="form-label">URL Slug </label>
                                <input
                                    type="text"
                                    className="form-control"
                                    value={data.slug}
                                    onChange={e => setData('slug', e.target.value)}
                                    placeholder="about-us"
                                />
                                {errors.slug && <div className="text-danger small">{errors.slug}</div>}
                                <div className="form-text">If the slug is empty it will be automatically generated by title</div>
                            </div>

                            <div className="mb-3 col-md-6">
                                <label className="form-label">Page Type <span className='text-danger'>*</span></label>
                                <select
                                    className="form-select"
                                    value={data.page_type}
                                    onChange={e => setData('page_type', e.target.value)}
                                >
                                    <option value="modular">Modular Content Pages</option>
                                    <option value="cms">CMS Section Pages</option>
                                </select>
                                {errors.page_type && <div className="text-danger small">{errors.page_type}</div>}
                                <div className="form-text">
                                    {data.page_type === 'cms' 
                                        ? 'Traditional pages with predefined sections' 
                                        : 'Flexible pages with modular content blocks and sections'
                                    }
                                </div>
                            </div>

                            <div className="mb-3 col-12">
                                <div className="form-check form-switch">
                                    <input
                                        type="checkbox"
                                        className="form-check-input"
                                        checked={data.is_published}
                                        onChange={e => setData('is_published', e.target.checked)}
                                        role="switch"
                                    />
                                    <label className="form-check-label">Publish Page</label>
                                </div>
                                <div className="form-text">Published pages are visible to visitors</div>
                            </div>
                        </div>

                        <div className="mt-4 pt-3 border-top">
                            <button 
                                type="submit" 
                                className="btn btn-primary me-2"
                                disabled={processing}
                            >
                                {processing ? (
                                    <>
                                        <span className="spinner-border spinner-border-sm me-2" />
                                        Creating...
                                    </>
                                ) : (
                                    'Create Page'
                                )}
                            </button>
                            <Link
                                href={route('pages.index')} 
                                className="btn btn-secondary"
                            >
                                Cancel
                            </Link>
                        </div>
                    </div>
                </form>
            </div>
        </>
    );
};

export default Create;